// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYmCmLELr6Y6QBDgAl92NDavIvLd8Hao',
    appId: '1:143454106728:web:a4aebc480ca007cc49f7dd',
    messagingSenderId: '143454106728',
    projectId: 'trackifit',
    authDomain: 'trackifit.firebaseapp.com',
    storageBucket: 'trackifit.firebasestorage.app',
    measurementId: 'G-BLHZM1MEEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ9qpwGD8DTe-SnCxJO6vUHgFxx5_mRmw',
    appId: '1:143454106728:android:35b50adc5a04b24849f7dd',
    messagingSenderId: '143454106728',
    projectId: 'trackifit',
    storageBucket: 'trackifit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KkzsoS8drCh0j_SCyqly8bah3frBmDs',
    appId: '1:143454106728:ios:235e51faec065f3249f7dd',
    messagingSenderId: '143454106728',
    projectId: 'trackifit',
    storageBucket: 'trackifit.firebasestorage.app',
    iosBundleId: 'com.example.trackifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KkzsoS8drCh0j_SCyqly8bah3frBmDs',
    appId: '1:143454106728:ios:235e51faec065f3249f7dd',
    messagingSenderId: '143454106728',
    projectId: 'trackifit',
    storageBucket: 'trackifit.firebasestorage.app',
    iosBundleId: 'com.example.trackifit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwYmCmLELr6Y6QBDgAl92NDavIvLd8Hao',
    appId: '1:143454106728:web:e9fa448350215fa649f7dd',
    messagingSenderId: '143454106728',
    projectId: 'trackifit',
    authDomain: 'trackifit.firebaseapp.com',
    storageBucket: 'trackifit.firebasestorage.app',
    measurementId: 'G-MLMWX7QDEJ',
  );
}
